services:
  - type: web
    name: app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    preDeployCommand: python run.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    build:
      cwd: .
