services:
  - type: web
    name: poultry-diagnosis
    env: python
    preDeployCommand: python run.py
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
    workingDir: .
    
