services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    build:
      cwd: .
